// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asrecasystiwpekpgtob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzcmVjYXN5c3Rpd3Bla3BndG9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTcxNzksImV4cCI6MjA2MDM5MzE3OX0.z-HhCBiDlVFX49F3PDdoW5qa3Tyi9PYDrd2GKmdZ0FM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);